[pytest]
log_cli = true
log_cli_level = DEBUG
testpaths = tests
pythonpath = .

addopts =
;    --collect-only
    -s
    -v
    -ra
    --strict-markers
    --tb=short

    --only-markers-prefix

    --better-report

markers =
    example: Marker for tests example.
    regular: Marker for regular tests.
    dummy: Marker for dummy tests.
    ONLY_X: Marker for tests that should be run only when explicitly specified.
    ONLY_Y: Marker for tests that should be run only when explicitly specified.
