[pytest]
log_cli = true
log_cli_level = DEBUG
testpaths = tests
pythonpath = .

addopts =
;    --collect-only
    -s
    -v
    -ra
    --strict-markers
    --tb=short

    --only-markers-prefix

    --better-report

markers =
    dummy_x: Dummy marker for testing purposes.
    dummy_y: Another dummy marker for testing purposes.
    ONLY_dummy_x: Marker to indicate that only tests with this marker should be run.
    ONLY_dummy_y: Marker to indicate that only tests with this marker should be run.

